spring.application.name=Notification
logging.pattern.console=%d{yyyy-MM-dd HH:mm:ss} | NotificationService | %X{method} | %X{correlationId} | %msg%n
app.name=Notification Service
app.message=default message
spring.profiles.active=qa,prod